

name: Deploy projeto no dockerhub / integracao com aws

on:
  push:
    branches: 
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout backend
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '8'
            - name: Build backend
              working-directory: backend/
              run: mvn clean install -DskipTests
            - name: Docker Login
              uses: docker/login-action@v2.1.0
              with:
                username: ${{ secrets.DOCKER_LOGIN }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker image backend
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: backend/
                push: true
                tags: timbeck1997/finnanceapp:latest, timbeck1997/finnanceapp:${{ github.run_number}}
            - name: Setup Node.js
              working-directory: frontend/
            - uses: actions/setup-node@v1
              with:
                node-version: 10.16
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
              with:
                context: frontend/
                push: true
                tags: timbeck1997/finnance-app-front:latest, timbeck1997/finnance-app-front:${{ github.run_number}}
              
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull timbeck1997/finnanceapp:latest
            - name: Remove docker container
              run: docker rm -f finnanceapp
            - name: Run docker container
              run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} --network=appnetwork -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} -e SPRING_PROFILES_ACTIVE=prod   --name finnanceapp timbeck1997/finnanceapp

   
