

name: Deploy projeto no dockerhub

on:
  push:
    branches: 
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up NODE
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      working-directory: frontend/
      run: npm ci 
    - name: Build
      working-directory: frontend/
      run: npm run build
    - name: Test
      working-directory: frontend/
      run: npm run test:ci
    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
        path: dist
    - name: Archive code coverage result
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_coverage
        path: coverage
        
      
      
    - name: Docker Compose Build
      working-directory: frontend/
      run: docker build -t finnanceapp:latest .
      
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: frontend/
        push: true
        tags: timbeck1997/finnanceapp:latest, timbeck1997/finnanceapp:${{ github.run_number}}
   
